server:
  port: 12001
spring:
  application:
    name: closer-fastDFS
  redis:
    host: 101.37.80.187
  rabbitmq:
    host: 101.37.80.187
    port: 5672
    username: guest
    password: HKC.1998
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true